include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-iolines

LUCI_TITLE:=LuCI I/O switcher
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
PKG_VERSION:=0.2.3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
