#!/bin/sh

# disable mode setting to any in modemnanager proto
[ -f /lib/netifd/proto/modemmanager.sh ] && {
	sed -i '/^[[:space:]]*modemmanager_set_allowed_mode "$device" "$interface" "any"$/s/.*/\t\t:/' /lib/netifd/proto/modemmanager.sh
}
