# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-simman
LUCI_DEPENDS:=+simman

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.2.6

PKG_RELEASE:=1

PKG_MAINTAINER:=Sklyarec Konstantin <atskyua@gmail.com> Vladimir Ovseychuk <vgovseychuk@gmail.com>

LUCI_TITLE:=LuCI SIM manager Configuration Frontend

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
