[modules]
log_file
#log_syslog

connlimit
ippool

# uncomment line for use protocl
pptp
#l2tp
#sstp
#pppoe
#ipoe

# auth
auth_mschap_v2
#auth_mschap_v1
#auth_chap_md5
#auth_pap

chap-secrets
#radius

#pppd_compat

#shaper
#logwtmp
#ipv6_nd
#ipv6_dhcp
#ipv6pool

[core]
log-error=/dev/stderr
thread-count=2

[common]
#single-session=replace
#max-sessions=0
#max-starting=0

[ppp]
verbose=1
min-mtu=1280
mtu=1400
mru=1400
accomp=deny
pcomp=deny
mppe=require
ipv4=require
ipv6=deny
lcp-echo-interval=20
lcp-echo-failure=3
lcp-echo-timeout=120
unit-cache=1

[auth]
#timeout=5
#max-failure=3
#noauth=0

[pptp]
verbose=1
ip-pool=pptp
ifname=pptp%d
#echo-interval=30

[pppoe]
verbose=1
interface=eth0
called-sid=mac
ip-pool=pppoe
ifname=pppoe%d
#ac-name=
#service-name=
#vlan-mon=eth0,10-200

[l2tp]
verbose=1
ip-pool=l2tp
ifname=l2tp%d
#secret=
#hello-interval=60

[sstp]
verbose=1
ifname=sstp%d
#ssl-pemfile=/etc/accel-ppp/sstp.crt
#ssl-keyfile=/etc/accel-ppp/sstp.key
#host-name=

[ipoe]
verbose=1
interface=eth0
username=ifname
shared=0
ifcfg=1
mode=L2
start=dhcpv4
lease-time=600
max-lease-time=3600
ip-pool=ipoe

[dns]
#dns1=
#dns2=

# Need Build with Radius support
[radius]
nas-identifier=accel-ppp
nas-ip-address=127.0.0.1
gw-ip-address=192.168.100.1
server=127.0.0.1,testing123,auth-port=1812,acct-port=1813,req-limit=50,fail-timeout=0,max-fail=10,weight=1
#dae-server=127.0.0.1:3799,testing123
verbose=1

[client-ip-range]
0.0.0.0/0

[ip-pool]
gw-ip-address=192.168.0.1
attr=Framed-Pool
192.168.0.2-255,name=pptp
192.168.1.2-255,name=pppoe
192.168.2.2-255,name=l2tp
192.168.3.2-255,name=sstp
192.168.4.2-255,name=ipoe

# Defalult log OpenWrt output 
[log]
log-file=/dev/stdout
log-emerg=/dev/stderr
log-fail-file=/dev/stdout
copy=1
level=3

# uncomment pppd_compat in [modules] if use ip-up/ip-down 
# native sctips are /etc/hotplug.d/iface/
#[pppd-compat]
#verbose=1
#ip-up=/etc/ppp/ip-up
#ip-down=/etc/ppp/ip-down
#radattr-prefix=/var/run/radattr

[chap-secrets]
gw-ip-address=192.168.100.1
#chap-secrets=/etc/ppp/chap-secrets

[shaper]
up-limiter=police
down-limiter=tbf
verbose=1

[cli]
verbose=1
telnet=127.0.0.1:2000
tcp=127.0.0.1:2001

[connlimit]
limit=10/min
burst=3
timeout=60

[ipv6-pool]
fc00:0:1::/48,64
delegate=fc00:1::/36,48

[ipv6-dns]
#fc00:1::1

[ipv6-dhcp]
verbose=1
pref-lifetime=604800
valid-lifetime=2592000
route-via-gw=1
