include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-report
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=LuCI report module
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
