include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-strongswan

LUCI_TITLE:=LuCI interface for Strongswan configuration
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
