# Custom configurator
#
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-smscontrol
LUCI_DEPENDS:=

# Version: <major>.<minor>.<patch>
PKG_VERSION:=0.2.0

PKG_RELEASE:=1

LUCI_TITLE:=LuCI utility to remote control via SMS

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
