include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-simman2

LUCI_TITLE:=LuCI interface for Simman2 configuration
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
