#!/bin/sh -x

if [ ! -f /etc/config/ttl ]; then
        touch /etc/config/ttl
        uci add ttl fw
	uci add ttl ttl
	uci add firewall include
	uci set firewall.@include[-1].path='/usr/share/ttl.sh'
	uci commit
fi
