#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service(){
	/usr/share/ttl.sh
	logger -t "TTL" "TTL reload"
}

reload_service(){
	(
		flock -n 9 || exit 0
		sleep 10 && start
	) 9>/var/lock/ttl-reload.lock &
}

service_triggers() {
	procd_add_reload_trigger ttl
}
