#!/bin/sh

# simple update firmware script for 132lan.ru site
# by Konstantine Shevlakov (c) 2025
# for correct OTA upgrade remote dir must have next iherarchy:
# www_root_dir/
#   latest/
#     changelog.txt - small note for update.
#     targets/
#       SoC_family/
#         SoC/
#           openwrt-${DISTRIB_RELEASE}-${PREFIX1}-${PREFIX2}-${YEAR}${MONTH}-rev${REVNUMBER}*.bin
#	    (e.g openwrt-24.10.2-4g-lte-202507-rev02-ramips-mt7621-beeline_smartbox-pro-squashfs-sysupgrade.bin)
#           profiles.json - list images generated by imagebuilder or buildroot
#
# In local firmware must be included local version in uci-defaults:
# /rom/etc/uci_defaults/fw_rev next body
#
#  FW_REV="${YEAR}${MONTH}-rev${REVNUMBER}"
#  e.g
#  FW_REV="202507-rev01"
#
# config URL Update server stored in
# /etc/config/ota
# config ota
# 	option url 'https://example.com/latest'
#
#
#       example
#
# config ota
# 	option url 'https://openwrt.132lan.ru/releases_cell/latest'

. /lib/functions.sh

PROGRESS_FILE=/tmp/ota_progress
VERSION_FILE=/tmp/ota_version

set_progress() {
	echo "$1" > ${PROGRESS_FILE}
}

load_config(){
        config_get url $1 url
}

config_load ota
config_foreach load_config

URL_BASE=$url

if [ "x${URL_BASE}" = "x" ]; then
	exit 0
fi

# Get OpenWrt Release info
[ -f /etc/openwrt_release ] && {
	. /etc/openwrt_release
	case ${DISTRIB_TARGET} in
		*x86*|*armsr*) echo "Current platform ${DISTRIB_TARGET} not supported." && exit 0 ;;
	esac
} || {
	echo "Unknown OpenWrt release!"
	exit 0
}

# Get board info
BOARD=$(jsonfilter -s "$(cat /etc/board.json)" -e '@["model"]["id"]')

# Remove update files
remove_files(){
	for f in firmware.bin changelog.txt; do
		[ -f /tmp/${f} ] && rm -rf /tmp/${f}
	done
}

case $1 in
	check)
		if [ ! -f /tmp/update.lock ]; then
			echo -e "Check updates from ${URL_BASE}\n"
		fi

		! [ -f /tmp/profiles.json ] && {
			wget ${URL_BASE}/targets/${DISTRIB_TARGET}/profiles.json -O /tmp/profiles.json > /dev/null 2>&1
		}

		! [ -f /tmp/profiles.json ] && {
			echo "Updates not available from this server."
			exit 0
		}

		[ -f /tmp/profiles.json ] && {
			[ ! -f /tmp/changelog.txt ] && {
				wget ${URL_BASE}/changelog.txt -O /tmp/changelog.txt > /dev/null 2>&1
			} || {
				break
			}
		} || {
			echo "No updates for this board: $BOARD" && remove_files && exit 0
		}
	;;
esac

# Get available boards
BASE_BOARD=$(jsonfilter -s "$(cat /tmp/profiles.json)" -e '@["profiles"][*]["supported_devices"].*')

# Get available board info
board_stuff(){
        IMAGES=$(jsonfilter -s "$(cat /tmp/profiles.json)" -e "@['profiles']['$FW_BOARD']['images'][*]" | grep sysupgrade)
        echo $IMAGES | jsonfilter \
                -e FILE="$['name']" \
                -e SHA256="$['sha256']" \
                -e FILESIZE="$['size']"
}

#sha256check(){
#}

# stuff
for b in $BASE_BOARD; do
	if [ "${b}" = "${BOARD}" ]; then
		FW_BOARD=$(echo $BOARD | sed -e 's/\,/_/')
		[ -f /tmp/profiles.json ] && {
			eval $(board_stuff)
		} || {
			echo "Failed! Abort update"
			remove_files
		}
		FW_REV_EXT=$(echo $FILE | awk -F [-] '{gsub("rev",""); gsub(/\./,"",$2);  print $2$5$6}')
		if [ -f /rom/etc/uci-defaults/fw_rev ]; then
			. /rom/etc/uci-defaults/fw_rev
			VER_LOCAL=$(echo $FW_REV | awk -F [-] '{gsub("rev",""); print $1$2}')
			DIGIT_RELEASE=$(echo ${DISTRIB_RELEASE} | awk '{gsub(/\./,""); print $0}')
			FW_VER_LOCAL=${DIGIT_RELEASE}${VER_LOCAL}
		else
			echo "Failed! Abort update"
			exit 0
		fi
		case $1 in
			upgrade)
			if [ -f /tmp/update.lock ]; then
				echo "Download firmware $FILE"
				echo "from $URL_BASE"
				set_progress "downloading 0"

				# Download with uclient-fetch, parse % from stderr progress bar
				uclient-fetch -O /tmp/firmware.bin ${URL_BASE}/targets/${DISTRIB_TARGET}/$FILE 2>&1 | while IFS= read -r line; do
					pct=$(echo "$line" | grep -o '[0-9]*%' | tr -d '%' | tail -1)
					[ -n "$pct" ] && set_progress "downloading $pct"
				done
				# Bash, not ash
				#DL_RC=${PIPESTATUS[0]:-$?}
				DL_RC=$?
				# ash-safe fallback: check file exists and non-empty
				[ -s /tmp/firmware.bin ] && DL_RC=0

				sleep 2
				case $DL_RC in
					0) echo "Download complete."
					   set_progress "downloading 100" ;;
					*) echo "Download failed for board: $BOARD"
					   set_progress "error download"
					   remove_files && exit 1 ;;
				esac

				sleep 2
				set_progress "verifying"
				SHA256_DL=$(sha256sum /tmp/firmware.bin | awk '{print $1}')
				echo -n "Check sha256 sum: "
				if [ "$SHA256" = "$SHA256_DL" ]; then
					echo "OK"
					echo "Update process start!"
					echo "Device will be rebooted."
					echo "DO NOT TURN OFF DEVICE!"
					sleep 2
					set_progress "testing"
					sysupgrade -T /tmp/firmware.bin
					case $? in
						0) echo "Flashing firmware" ;;
						*) echo "Failed! Abort update"
						   set_progress "error verify"
						   remove_files && exit 1 ;;
					esac
					sleep 2
					set_progress "flashing"
					rm -rf /tmp/update.lock /tmp/profiles.json /tmp/changelog.txt
					# Exit cleanly before sysupgrade takes over
					sleep 30 && sysupgrade /tmp/firmware.bin &
					exit 0
				else
					echo "Failed! Abort update."
					set_progress "error sha256"
					remove_files && rm -rf /tmp/update.lock /tmp/profiles.json
					exit 1
				fi
			fi
			;;
			check)
			. /usr/lib/os-release
			if [ $FW_REV_EXT -gt $FW_VER_LOCAL ]; then
				echo "New firmware upgrade release!"
				echo -e "*** $FILE ***\n"
				[ -r /tmp/changelog.txt ] && {
					echo -e "RELEASE NOTES:\n"
					echo "$(cat /tmp/changelog.txt)"
				}
				echo ""
				echo "Please run script again for download and install update!"
				touch /tmp/update.lock
				# Write version info for LuCI
				# Extract prefix (everything before YYYYMM date) from remote filename
				VER_PREFIX=$(echo $FILE | sed 's/-[0-9]\{6\}-rev[0-9]*-.*//')
				VER_UPGRADE="${VER_PREFIX}-$(echo $FILE | sed 's/.*-\([0-9]\{6\}-rev[0-9]*\)-.*/\1/')"
				VER_CURRENT="${VER_PREFIX}-${FW_REV}"
				printf "current=%s\nupgrade=%s\n" "$VER_CURRENT" "$VER_UPGRADE" > ${VERSION_FILE}
			else
				echo "Update not found!"
				# Write only current version using OPENWRT_RELEASE prefix + local FW_REV
				printf "current=%s\nupgrade=\n" "${OPENWRT_RELEASE%~*} $FW_REV" > ${VERSION_FILE}
			fi
			;;
		esac
	fi
done

#rm -f /tmp/profiles.json /tmp/update.lock /tmp/changelog.txt
