#!/bin/sh

PATH='/usr/bin:/usr/sbin:/bin:/sbin'

source /usr/lib/telegram-bot/variables

api="https://api.telegram.org/bot$key"

if [ ! -d "/tmp/telegram-bot" ]; then
  mkdir /tmp/telegram-bot
fi

#telegram_log_file=/tmp/telegram-bot/telegram.log
#cmd_log_file=/tmp/telegram-bot/telegram_cmd.log
telegram_log_file=/dev/null
cmd_log_file=/dev/null

offset_file=/tmp/telegram-bot/telegram_offset

curl -k -s -X POST $api/sendMessage -d chat_id=$my_chat_id -d parse_mode=Markdown --data-urlencode text="Router started." &> $telegram_log_file

polling_timeout=30
offset=0
if [ -f "$offset_file" ] ; then
	offset=$( cat $offset_file )
else
	echo $offset > $offset_file
fi

reply_to_msg () {
	msg_id=$1
	origin=$2
	eval toReturn="$3"
        curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=HTML --data-urlencode text="$toReturn" &> $telegram_log_file
}

while [ true ]
do
	updates=$(curl -s -k -X GET ${api}/getUpdates?offset=${offset}&timeout=${polling_timeout})
	status=$(jsonfilter -s "$updates" -e $.ok)
	if [ $status = 'true' ]; then
		update_ids=$(jsonfilter -s "$updates" -e $.result[*].update_id)
		for update_id in $update_ids
		do
			offset=$((update_id+1))
			echo $offset > $offset_file
			origin=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.chat.id")
			msg_id=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.message_id")
			command=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.text")
			is_a_cmd=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.entities[*].type")
			query_ans=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].callback_query.id")
			origin_ans=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].callback_query.message.chat.id")
			if [[ "$origin" != "$my_chat_id" && "$origin_ans" != "$my_chat_id" ]];then
				curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="This is a Private bot." &> $telegram_log_file
				curl -k -s -X POST $api/leaveChat -d chat_id=$origin  &> $telegram_log_file
			else
				if [ "$is_a_cmd" ==  "bot_command" ]; then
					
					cmd=$(echo $command | awk '{print $1}')
					param=$(echo $command | awk '{$1="";print $0}')
					DATE=`date +%Y-%m-%d_%H:%M:%S`
					RETURN_TEXT=""
					case "$cmd" in
						("/start")
	                                                RETURN_TEXT=$(printf "/memory Return memory (RAM) info\n/clients List of connected clients\n/reboot Reboot the device\n/wanip WAN ip address")
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
							;;
						("/reboot")
                                                	echo "[ $DATE ] reboot!" >> $cmd_log_file
	                                                RETURN_TEXT="Command executed!"
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}" && sleep 5 && reboot
							;;
						("/memory")
							echo "[ $DATE ] memory!" >> $cmd_log_file
							clients=$("/usr/lib/telegram-bot/functions/memory_info.sh")
							RETURN_TEXT="$(printf "Memory informations: \n$clients")"
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
                                                        ;;
						(*)
							if [ -f "/usr/lib/telegram-bot/functions/${cmd}.sh" ] ; then
								echo "[ $DATE ] $cmd !" >> $cmd_log_file
								RETURN_TEXT=$("/usr/lib/telegram-bot/functions/${cmd}.sh")
							else
								echo "[ $DATE ] $cmd command not enabled" >> $cmd_log_file
                                    		        	RETURN_TEXT="This command is not enabled."
							fi

                                                        reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
							;;
                                    	esac

				else
 					curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="Is not a command." &> $telegram_log_file
				fi

			fi
		done
	fi
	sleep 1
done&
