include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pollmydevice
LUCI_DEPENDS:= +pollmydevice

PKG_VERSION:=0.9

PKG_RELEASE:=1

LUCI_TITLE:=LuCI TCP to RS232 and RS485 Configuration Frontend

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
